[package]
name = "eva-engine"
version = "0.1.0"
edition = "2024"
default-run = "eva-engine-cli"

[dependencies]
rt-common = { git = "https://github.com/Yurand2000/rt-common.git" }
clap = { version = "4.5.48", features = ["derive"] }
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"

[[bin]]
name = "eva-engine-cli"
path = "src/cli-bin/main.rs"

[[bin]]
name = "mpr_fp_gen"
path = "src/bin/mpr_fp_gen.rs"